name: Application CD

on:
  workflow_call:

permissions:
  checks: write
  id-token: write
  contents: write
  security-events: write

env:
  api_directory: ./Server

jobs:
  server-deploy:
    name: Server Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: "eu-west-1"
          role-session-name: Deployment_CD_GitHub_to_AWS_via_FederatedOIDC

      - name: Create API Package
        working-directory: ${{ env.api_directory }}
        run: | 
          zip -r ../api.zip .

      - name: Deploy Server
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ env.AWS_SESSION_TOKEN }}
          application_name: project-tracker-app
          environment_name: project-tracker-env
          version_label: "project-tracker-deployment-${{ github.sha }}"
          region: eu-west-1
          deployment_package: api.zip
          existing_bucket_name: project-tracker-deploy-bucket
