name: CI

on:
  workflow_call:
  pull_request:
    branches: []

permissions:
  checks: write
  contents: read
  id-token: write
  security-events: write

jobs:
  terraform-ci:
    name: "Terraform CI"
    secrets: inherit
    uses: ./.github/workflows/terraform-ci.yaml

  test-database-migration:
    name: "Flyway Migration Testing"
    secrets: inherit
    uses: ./.github/workflows/db-ci.yaml
